from typing import List, Dict, Tuple, Any

def seed(newSeed: int) -> None: ... 
def random() -> float: ... 
def uniform(a: float, b: float) -> float: ... 
def randint(a: int, b: int) -> int: ... 
def randRange(minV: float, maxV: float) -> float: ... 
def randRange(minV: int, maxV: int) -> int: ... 
def randRange(minV: cave.Vector2, maxV: cave.Vector2) -> cave.Vector2: ... 
def randRange(minV: cave.Vector3, maxV: cave.Vector3) -> cave.Vector3: ... 
def randRange(minV: cave.Vector4, maxV: cave.Vector4) -> cave.Vector4: ... 
def perlin(x: float) -> float: ... 
def perlin(x: float, y: float) -> float: ... 
def perlin(x: float, y: float, z: float) -> float: ... 
def perlin(pos: cave.Vector2) -> float: ... 
def perlin(pos: cave.Vector3) -> float: ... 

